### PR TITLE
Add Slack verification for Hack Night

### PR DESCRIPTION
**Pull request by tetraoxygen**
Add a redirect to the Slack OAuth stuff for Hack Night.

Credit to @YodaLightsabr for lots of help with this patch.

### CODE REVIEW

**Comment by YodaLightsabr** [comment]
Oh shoot @tetraoxygen I don't think we fixed the object generation for the other OAuth url.

**Comment by tetraoxygen** [comment]
I'm at my machine right now — give me a few minutes.

**Comment by YodaLightsabr** [comment]
Yeah we just have to convert this into an object.

image

**Comment by tetraoxygen** [comment]
Done, pushing now

**Comment by tetraoxygen** [comment]
That should do it 🤞🏻

**Comment by maxwofford** [comment]
This looks awesome @tetraoxygen @YodaLightsabr, great work! Seems like it's still being touched, so LMK when it's ready for review.

**Comment by YodaLightsabr** [comment]
Not yet, because I'm not sure how it'll work without the Zoom API keys. It's likely that it errors out, so it would be nice if there was a second instance for testing.

**Comment by maxwofford** [comment]
DM'ing you on Slack!

**Comment by YodaLightsabr** [comment]
I just tested it and it works as intended. A potential improvement would be to remember that the user logged in, but it might require some database work.

**Comment by maxwofford** [comment]
Merged in the interest of time b/c Hack Night is happening right now. Sent a bug report directly to @tetraoxygen in the interest of keeping it private while they work it out.

**Pull request merged**
