### PR TITLE
Change hard-coded slack client ids to use env vars

### PR DESCRIPTION
**Pull request by grymmy**
This afternoon I set up the full slash-z debugging environment.  There are two components (on our side) of this:

1. A clone of the [gcal integration](https://github.com/hackclub/slash-z-google-calendar) (clasp/Google appscript):
Screenshot 2023-03-18 at 7 12 02 PM

2. [/z](https://github.com/hackclub/slash-z) running locally and exposed remotely via ngrok.
Screenshot 2023-03-18 at 7 53 34 PM
Screenshot 2023-03-18 at 7 13 39 PM

With this setup, I was able to carefully step with a debugger through the entirety of the flow.  I had to modify many URLs on both the gcal and slash-z side to configure it correctly.  I had some additional observability on script.google.com side of things as such:
Screenshot 2023-03-18 at 7 55 47 PM

After modifying a lot of URLs on the slash-z service side, **I was able to see the entirety of the gcal integration work without any changes to the logic** - only URLs.

One of the very notable changes I had to make on the slash-z service side to get this working were two lines (see this PR) that had hard-coded client-id's that were not grabbed from environment variables.  They should, but do not match the configuration currently set in slash-z, and you can notice that these are localized to code specifically dealing with new scheduling links - I believe this could explain perfectly the Slack auth errors we are seeing in gcal integration and hack.af/night for unauthenticated users only.
Screenshot 2023-03-18 at 5 14 49 PM

### CODE REVIEW

**Comment by YodaLightsabr** [comment]
This looks good! Have the Heroku env vars been updated?

**Comment by grymmy** [comment]
> This looks good! Have the Heroku env vars been updated? 

The env vars are already correct, just not being used.

**Review by YodaLightsabr — APPROVED** [review]
Ah, okay. LGTM!

**Review by DestroyerXyz — APPROVED** [review]

**Comment by DestroyerXyz** [comment]
Great work! 🎉

**Pull request merged**
