### PR TITLE
Send data to slack api as form data 

### PR DESCRIPTION
**Pull request by DestroyerXyz**
Send data to https://slack.com/api/oauth.v2.access as form data as said in https://api.slack.com/methods/oauth.v2.access

### CODE REVIEW

**Comment by grymmy** [comment]
I will be spending time on this sometime tomorrow and will attempt to set up the full end-to-end debugging environment, will patch w/ this PR and test and report back here with updates if I make progress

**Comment by grymmy** [comment]
FYI - I will merge this PR after testing it locally to ensure it functions as expected.

**Comment by DestroyerXyz** [comment]
Is this still going to get merged? Just checking

**Comment by grymmy** [comment]
Yes I will try to find time today to test, sorry, been busy with Sinerider and other things

**Pull request merged**
